# Generated by Django 5.2.7 on 2026-05-05 13:50

import django.db.models.deletion
import utils.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adjfeedback', '0019_merge_20241106_0903'),
        ('participants', '0030_adjudicator_registration_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('primary_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='primary email')),
                ('extra_emails', models.JSONField(blank=True, default=list, verbose_name='extra emails')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='external ID')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'judge profile',
                'verbose_name_plural': 'judge profiles',
                'ordering': ['-active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackExportEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('sent', 'sent'), ('failed', 'failed'), ('permanent_failed', 'permanently failed')], db_index=True, default='pending', max_length=20, verbose_name='status')),
                ('idempotency_key', models.CharField(max_length=120, unique=True, verbose_name='idempotency key')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='attempts')),
                ('next_attempt_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='next attempt at')),
                ('last_error', models.TextField(blank=True, verbose_name='last error')),
                ('last_http_status', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='last HTTP status')),
                ('payload_hash', models.CharField(blank=True, max_length=64, verbose_name='payload hash')),
                ('payload', models.JSONField(blank=True, null=True, verbose_name='payload')),
                ('remote_response', models.JSONField(blank=True, null=True, verbose_name='remote response')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('feedback', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='export_event', to='adjfeedback.adjudicatorfeedback', verbose_name='feedback')),
            ],
            options={
                'verbose_name': 'feedback export event',
                'verbose_name_plural': 'feedback export events',
                'ordering': ['status', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='JudgeProfileLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('adjudicator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='judge_profile_link', to='participants.adjudicator', verbose_name='adjudicator')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='feedbackexport.judgeprofile', verbose_name='judge profile')),
            ],
            options={
                'verbose_name': 'judge profile link',
                'verbose_name_plural': 'judge profile links',
            },
        ),
        migrations.CreateModel(
            name='GlobalFeedbackExportPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('view.feedback_export', 'view feedback export'), ('manage.feedback_export', 'manage feedback export')], max_length=50, verbose_name='permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'global feedback export permission',
                'verbose_name_plural': 'global feedback export permissions',
                'constraints': [utils.models.UniqueConstraint(fields=('user', 'permission'), name='feedbac_globalfeedbackexportpermission_user__permission_uniq')],
            },
        ),
    ]
