# Generated by Codex on 2026-03-14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("draw", "0010_alter_debateteam_side_alter_teamsideallocation_side"),
    ]

    operations = [
        migrations.CreateModel(
            name="ByeTeamOverride",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("round", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="bye_team_override", to="tournaments.round", verbose_name="round")),
                ("team", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="participants.team", verbose_name="team")),
            ],
            options={
                "verbose_name": "bye team override",
                "verbose_name_plural": "bye team overrides",
            },
        ),
    ]
