# Generated by Codex on 2026-04-06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("draw", "0011_byteteamoverride"),
        ("draw", "0011_debate_scheduled_at"),
    ]

    operations = []
