# Generated by Django 5.2.7 on 2026-08-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0030_adjudicator_registration_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='seed',
            field=models.PositiveIntegerField(blank=True, help_text='Used as initial ranking to power-pair the first round, and to order teams for round-robin draws (including BP preset schedules, which require unique seeds 1 through n).', null=True, verbose_name='seed'),
        ),
    ]
