# Generated by Django 5.2.7 on 2026-04-28 22:42

import django.db.models.deletion
import utils.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0030_adjudicator_registration_status_and_more'),
        ('tournaments', '0015_alter_round_draw_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('league', models.CharField(choices=[('SDL', 'Slovak Debate League'), ('JDL', 'Junior Debate League')], max_length=3, verbose_name='league')),
                ('regional_slots', models.PositiveSmallIntegerField(default=0, verbose_name='regional final slots')),
                ('invited_teams', models.PositiveSmallIntegerField(default=0, verbose_name='invited teams')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'break season',
                'verbose_name_plural': 'break seasons',
                'ordering': ['-active', '-created_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BreakAdjudicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='participants.institution', verbose_name='institution')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjudicators', to='seasonbreaks.breakseason', verbose_name='season')),
            ],
            options={
                'verbose_name': 'season break adjudicator',
                'verbose_name_plural': 'season break adjudicators',
                'ordering': ['season', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BreakRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('seq', models.PositiveSmallIntegerField(default=0, verbose_name='sequence')),
                ('source_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='participants.region', verbose_name='source region')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='seasonbreaks.breakseason', verbose_name='season')),
            ],
            options={
                'verbose_name': 'break region',
                'verbose_name_plural': 'break regions',
                'ordering': ['season', 'seq', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BreakAdjudicatorLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjudicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='break_links', to='participants.adjudicator', verbose_name='adjudicator')),
                ('break_adjudicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='seasonbreaks.breakadjudicator', verbose_name='season adjudicator')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjudicator_links', to='seasonbreaks.breakseason', verbose_name='season')),
            ],
            options={
                'verbose_name': 'break adjudicator link',
                'verbose_name_plural': 'break adjudicator links',
            },
        ),
        migrations.CreateModel(
            name='BreakSpeaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='seasonbreaks.breakseason', verbose_name='season')),
            ],
            options={
                'verbose_name': 'season break speaker',
                'verbose_name_plural': 'season break speakers',
                'ordering': ['season', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BreakSpeakerLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='seasonbreaks.breakspeaker', verbose_name='season speaker')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker_links', to='seasonbreaks.breakseason', verbose_name='season')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='break_links', to='participants.speaker', verbose_name='speaker')),
            ],
            options={
                'verbose_name': 'break speaker link',
                'verbose_name_plural': 'break speaker links',
            },
        ),
        migrations.CreateModel(
            name='BreakTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='participants.institution', verbose_name='institution')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='seasonbreaks.breakregion', verbose_name='home region')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='seasonbreaks.breakseason', verbose_name='season')),
            ],
            options={
                'verbose_name': 'season break team',
                'verbose_name_plural': 'season break teams',
                'ordering': ['season', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BreakTeamLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='seasonbreaks.breakteam', verbose_name='season team')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_links', to='seasonbreaks.breakseason', verbose_name='season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='break_links', to='participants.team', verbose_name='team')),
            ],
            options={
                'verbose_name': 'break team link',
                'verbose_name_plural': 'break team links',
            },
        ),
        migrations.CreateModel(
            name='BreakTournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveSmallIntegerField(default=0, verbose_name='sequence')),
                ('frozen_at', models.DateTimeField(blank=True, null=True, verbose_name='frozen at')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='break_tournaments', to='seasonbreaks.breakregion', verbose_name='region')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='break_tournaments', to='seasonbreaks.breakseason', verbose_name='season')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='break_tournaments', to='tournaments.tournament', verbose_name='tournament')),
            ],
            options={
                'verbose_name': 'break tournament',
                'verbose_name_plural': 'break tournaments',
                'ordering': ['season', 'seq', 'tournament__seq', 'tournament__name'],
            },
        ),
        migrations.CreateModel(
            name='BreakTeamTournamentResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.FloatField(default=0, verbose_name='wins')),
                ('ballots', models.FloatField(default=0, verbose_name='ballots')),
                ('speaker_score', models.FloatField(default=0, verbose_name='speaker score')),
                ('rounds_debated', models.PositiveSmallIntegerField(default=0, verbose_name='rounds debated')),
                ('majority_debated', models.BooleanField(default=False, verbose_name='debated majority of rounds')),
                ('break_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_results', to='seasonbreaks.breakteam', verbose_name='season team')),
                ('break_tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_results', to='seasonbreaks.breaktournament', verbose_name='break tournament')),
            ],
            options={
                'verbose_name': 'break team tournament result',
                'verbose_name_plural': 'break team tournament results',
                'ordering': ['break_tournament', '-wins', '-ballots', '-speaker_score'],
            },
        ),
        migrations.CreateModel(
            name='BreakSpeakerTournamentParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speeches', models.PositiveSmallIntegerField(default=0, verbose_name='speeches')),
                ('rounds', models.PositiveSmallIntegerField(default=0, verbose_name='rounds')),
                ('break_speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_participations', to='seasonbreaks.breakspeaker', verbose_name='season speaker')),
                ('break_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker_participations', to='seasonbreaks.breakteam', verbose_name='season team')),
                ('break_tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker_participations', to='seasonbreaks.breaktournament', verbose_name='break tournament')),
            ],
            options={
                'verbose_name': 'break speaker tournament participation',
                'verbose_name_plural': 'break speaker tournament participations',
                'ordering': ['break_tournament', 'break_team', 'break_speaker'],
            },
        ),
        migrations.CreateModel(
            name='BreakAdjudicatorTournamentStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chair_count', models.PositiveSmallIntegerField(default=0, verbose_name='chairs')),
                ('panellist_count', models.PositiveSmallIntegerField(default=0, verbose_name='panellists')),
                ('trainee_count', models.PositiveSmallIntegerField(default=0, verbose_name='trainees')),
                ('total_count', models.PositiveSmallIntegerField(default=0, verbose_name='total')),
                ('break_adjudicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_stats', to='seasonbreaks.breakadjudicator', verbose_name='season adjudicator')),
                ('break_tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjudicator_stats', to='seasonbreaks.breaktournament', verbose_name='break tournament')),
            ],
            options={
                'verbose_name': 'break adjudicator tournament stats',
                'verbose_name_plural': 'break adjudicator tournament stats',
                'ordering': ['break_tournament', 'break_adjudicator'],
            },
        ),
        migrations.CreateModel(
            name='GlobalBreaksPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('view.breaks', 'view global breaks'), ('edit.breaks', 'edit global breaks'), ('manage.breaks_access', 'manage global breaks access')], max_length=50, verbose_name='permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'global breaks permission',
                'verbose_name_plural': 'global breaks permissions',
            },
        ),
        migrations.AddConstraint(
            model_name='breakregion',
            constraint=utils.models.UniqueConstraint(fields=('season', 'name'), name='seasonb_breakregion_season__name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='breakadjudicatorlink',
            constraint=utils.models.UniqueConstraint(fields=('season', 'adjudicator'), name='seasonb_breakadjudicatorlink_season__adjudicator_uniq'),
        ),
        migrations.AddConstraint(
            model_name='breakspeakerlink',
            constraint=utils.models.UniqueConstraint(fields=('season', 'speaker'), name='seasonb_breakspeakerlink_season__speaker_uniq'),
        ),
        migrations.AddConstraint(
            model_name='breakteam',
            constraint=utils.models.UniqueConstraint(fields=('season', 'name'), name='seasonb_breakteam_season__name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='breakteamlink',
            constraint=utils.models.UniqueConstraint(fields=('season', 'team'), name='seasonb_breakteamlink_season__team_uniq'),
        ),
        migrations.AddConstraint(
            model_name='breaktournament',
            constraint=utils.models.UniqueConstraint(fields=('season', 'tournament'), name='seasonb_breaktournament_season__tournament_uniq'),
        ),
        migrations.AddConstraint(
            model_name='breakteamtournamentresult',
            constraint=utils.models.UniqueConstraint(fields=('break_tournament', 'break_team'), name='seasonb_breakteamtournamentresult_break_tournament__break_team_uniq'),
        ),
        migrations.AddConstraint(
            model_name='breakspeakertournamentparticipation',
            constraint=utils.models.UniqueConstraint(fields=('break_tournament', 'break_speaker', 'break_team'), name='seasonb_breakspeakertournamentparticipation_break_tournament__break_speaker__break_team_uniq'),
        ),
        migrations.AddConstraint(
            model_name='breakadjudicatortournamentstats',
            constraint=utils.models.UniqueConstraint(fields=('break_tournament', 'break_adjudicator'), name='seasonb_breakadjudicatortournamentstats_break_tournament__break_adjudicator_uniq'),
        ),
        migrations.AddConstraint(
            model_name='globalbreakspermission',
            constraint=utils.models.UniqueConstraint(fields=('user', 'permission'), name='seasonb_globalbreakspermission_user__permission_uniq'),
        ),
    ]
