# Generated by Django 5.2.7 on 2026-06-16 21:04

import django.db.models.deletion
import utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasonbreaks', '0007_breakregion_expected_tournaments'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakCutoffAdvancement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutoff_advancements', to='seasonbreaks.breakteam', verbose_name='season team')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutoff_advancements', to='seasonbreaks.breakregion', verbose_name='region')),
            ],
            options={
                'verbose_name': 'break cutoff advancement',
                'verbose_name_plural': 'break cutoff advancements',
                'constraints': [utils.models.UniqueConstraint(fields=('region', 'break_team'), name='seasonb_breakcutoffadvancement_region__break_team_uniq')],
            },
        ),
    ]
