# Generated by Django 5.2.7 on 2026-04-29 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0015_alter_round_draw_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('seq', models.IntegerField(blank=True, null=True, verbose_name='sequence number')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'tournament category',
                'verbose_name_plural': 'tournament categories',
                'ordering': ['seq', 'name'],
            },
        ),
        migrations.AddField(
            model_name='tournament',
            name='homepage_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments', to='tournaments.tournamentcategory', verbose_name='homepage category'),
        ),
    ]
