# Generated by Codex on 2026-05-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0016_tournamentcategory_tournament_homepage_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentcategory',
            name='public',
            field=models.BooleanField(default=True, help_text='Public categories are shown to everyone. Private categories are shown only to superusers and users with administrator access to at least one tournament in the category.', verbose_name='public'),
        ),
    ]
