# Generated by Claude on 2026-06-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0017_tournamentcategory_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='tournaments.tournamentcategory', help_text='The category this one is nested inside, if any. Top-level categories have no parent.', verbose_name='parent category'),
        ),
    ]
